<?php

namespace Acme\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository{
	public function findAllOrderedByNombre()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM AcmeUserBundle:Author a ORDER BY a.nombre ASC')
            ->getResult();
    }
}