<?php

namespace Acme\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MunicipalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipalityRepository extends EntityRepository
{
}