<?php

namespace Acme\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * personRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personRepository extends EntityRepository
{
}