user:
    pattern: /
    defaults: {_controller: AcmeUserBundle:User:index }

user_update:
    pattern: /{id}/update
    defaults: {_controller: AcmeUserBundle:User:update }

user_show:
    pattern: /{id}/show
    defaults: {_controller: AcmeUserBundle:User:show }

user_edit:
    pattern: /{id}/edit
    defaults: {_controller: AcmeUserBundle:User:edit }

user_new:
    pattern: /new
    defaults: {_controller: AcmeUserBundle:User:new }

user_create:
    pattern: /create
    defaults: {_controller: AcmeUserBundle:User:create}

user_delete:
    pattern: /{id}/delete
    defaults: {_controller: AcmeUserBundle:User:delete }